### PR TITLE
Debounce the invocation of the open method - fixes #1138

### LINKED ISSUE #1138: Chrome version 73 causing problems
In Chrome 73 desktop we're seeing various odd behaviors in both the newest version of pickadate and the older version we were using. 

One user reported the datepicker opens as soon as the page loads instead of waiting for him to click on the input. (unable to reproduce as of yet).

I myself am seeing the datepicker close and run the OnClose event immediately after clicking to open it.

On the examples on your demo site https://amsul.ca/pickadate.js/, I'm seeing what appears to be the datepicker opening twice; it flashes up, then flashes down, then flashes up again. In the console, for the events example that logs the events I see "opened up", "closed now", and then "opened up" again.

I don't see any of this behavior in Edge or Firefox. I also didn't see the problem in Chrome 72,

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

File: lib/picker.js [hunk 1]
```diff
@@ -607,7 +607,21 @@ function PickerConstructor( ELEMENT, NAME, COMPONENT, OPTIONS ) {
         ) //endreturn
     } //createWrappedComponent
 
-
+    // taken from https://davidwalsh.name/javascript-debounce-function
+    function debounce(func, wait, immediate) {
```
Comment (amsul) [inline lib/picker.js]: This should probably be defined outside of the PickerConstructor..maybe next to where we have `getRealEventTarget`

File: lib/picker.js [hunk 2]
```diff
@@ -629,10 +643,11 @@ function PickerConstructor( ELEMENT, NAME, COMPONENT, OPTIONS ) {
             ).
 
             // On focus/click, open the picker.
-            on( 'focus.' + STATE.id + ' click.' + STATE.id, function(event) {
+            on( 'focus.' + STATE.id + ' click.' + STATE.id,
+            debounce(function(event) {
                 event.preventDefault()
                 P.open()
-            })
+            }, 300))
```
Comment (amsul) [inline lib/picker.js]: 300 seems rather long..if it's a race condition introduced in Chrome 73, I can't imagine it would need that long 🤔

Comment (amsul) [reply lib/picker.js]: We should also add a comment here as to why it's debounced (with a reference to the issue).

File: tests/units/base.js [hunk 3]
```diff
@@ -464,37 +475,69 @@ module( 'Base keyboard events', {
...
+                                        QUnit.start();
+                                    }, 500)
+                                }, 500)
+                            }, 500)
+                        }, 500)
+                    }, 500)
+                }, 500)
+            }, 500)
+        }, 500)
+    }, 500)
```
Comment (amsul) [inline tests/units/base.js]: Oh my 😯 lol

Comment (amsul) [reply tests/units/base.js]: Yeah, I suppose it's either this, or using lolex.

But on second thought, considering this is v3, I'd rather us spend less effort adding more dependencies.

File: tests/units/base.js [hunk 4]
```diff
@@ -425,26 +425,37 @@ module( 'Base mouse events', {
...
     var picker = this.picker
 
     picker.$node.click()
-    ok( picker.get( 'open' ) === true, 'Opened with click in' )
-
-    $( 'body' ).click()
-    ok( picker.get( 'open' ) === false, 'Closed with click out' )
+    setTimeout(function() {
+        ok( picker.get( 'open' ) === true, 'Opened with click in' )
+        // QUnit.start();
```
Comment (amsul) [inline tests/units/base.js]: I guess we don't need that

File: lib/picker.js (hunk 1 above)
Comment (DanielRuf) [reply lib/picker.js]: Ok, will change this later today.

File: lib/picker.js (hunk 2 above)
Comment (DanielRuf) [reply lib/picker.js]: Ok, which value would you recommend? 100ms or lower?

File: tests/units/base.js (hunk 4 above)
Comment (DanielRuf) [reply tests/units/base.js]: Do you mean the comment?

File: tests/units/base.js (hunk 3 above)
Comment (DanielRuf) [reply tests/units/base.js]: Unfortunately I know / knew no other direct solution as we uss QUnit 1 and did not want to touch more dependencies for this.

**Comment by DanielRuf** [comment]
I have applied the proposed changes. When we are ready to merge I will squash the commits into one.

File: lib/picker.js (hunk 2 above)
Comment (amsul) [reply lib/picker.js]: I would assume that since it's a race condition at the browser level, we wouldn't need anything more than a few milliseconds. To be safe, I think just 50ms should be sufficient. At 100ms, it starts to impact the experience minutely.

**Comment by amsul** [comment]
@DanielRuf I think we're ready to merge em in. We can ship a new build for 3.6.1 after.

**Comment by DanielRuf** [comment]
I'll do the change to 50 instead of 100 ms and then squash the commits

**Comment by DanielRuf** [comment]
Ready to be merged. Thanks for the feedback.

**Comment by colinhowe** [comment]
Hi, we've just hit this on our site. Using the most recent version of pickadate we're seeing that the close event is being fired immediately after opening ~50% of the time. If you want to replicate it consistently you need to do a long click on the input box (which explains why it happens 50% of the time). When the click is fired it is using the input box as the target element and totally ignoring the new element that has appeared.

You can see this behaviour on the demo site: https://amsul.ca/pickadate.js/

This behaviour only started in Chrome 73 and is not present in Safari 12.0.3.

The dirty fix that springs to mind is to have the open handler register whether the opening click has completed or not. If the click has not been completed then the close handler should do a no-op.

**Comment by DanielRuf** [comment]
Hi @colinhowe, please read the PR and the comments and see the changes. This is a regression in Chrome. This PR is just a workaround to fix it.

**Comment by DanielRuf** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=941910

**Comment by DanielRuf** [comment]
> This behaviour only started in Chrome 73 and is not present in Safari 12.0.3.

Because webKit !== Chromium ;-)

**Comment by colinhowe** [comment]
I realise that about Safari. It was more to give additional context. Anyway, I've tracked down what has happened in Chromium. I'll raise a PR as I believe the issue we're seeing is different to this one.

**Comment by DanielRuf** [comment]
No, it is the exact same issue which is fixed by this PR.

**Comment by DanielRuf** [comment]
Please try the patch / changes of this PR.

**Comment by colinhowe** [comment]
I am using `master` which contains this PR. It is not the exact same issue. You can replicate on your own demo page which is also running this PR.

1. Go to https://amsul.ca/pickadate.js/
2. Click and hold on the picker
3. Release

Expected behaviour: calendar stays open
Actual behaviour: it closes

**Comment by DanielRuf** [comment]
It is the same imo.
The website does not use the latest release afaik.

**Comment by DanielRuf** [comment]
> * Click and hold on the picker
> * Release

No one does this. You have to increase the timeout to dethrottle it. The cause is still the same.

**Comment by colinhowe** [comment]
The website uses 3.6.2 - I did check before sending you the instructions.

The instructions are purposefully exaggerated. All you have to do is be slow enough between mousedown and mouseup to trigger a DOM change. I figured saying 'click for ~50ms' would be less helpful.

As a general fyi, older people do use the internet. They do click slowly.

**Comment by gregblass** [comment]
FYI - I just had a client let me know that on some slower machines, 100ms doesn't seem to be enough to do the trick.

**Comment by DanielRuf** [comment]
@gregblass we are aware of it and there is an open issue which tries a different workaround.

**Comment by gregblass** [comment]
Got it! Hey would you mind linking me to that?

**Comment by DanielRuf** [comment]
See https://github.com/amsul/pickadate.js/pull/1145

**Comment by ivanvgh** [comment]
> @DanielRuf I'm sorry. I should have been more active and send the patches to these repos myself. I also got this datepicker and slider repo which I recall I had discussion with you about confused.
> 
> Anyhow, the quick fix for this one will be just asking the UA to route the up events to the same input elements that started this with so that the logic of dismissing the popup due to the click handler doesn't get triggered. So before I send the patch and the real fix, could you load [this page](https://amsul.ca/pickadate.js/). I assume this still has the bad behavior here (i.e. popup closing if the user does a long click). Is that right? I'm not familiar with the versioning of this library but I just want to make sure we test the patch on a live example that does show the problem.
> 
> Now just open the devtools and paste this code:
> 
> ```js
> document.querySelector('.picker__input').addEventListener('pointerdown', e=>e.target.setPointerCapture(e.pointerId));
> ```
> 
> It should fix the problem for the first date picker. Do you see any problem after this patch to that page?

you are rigth, but that does not fix the whole problem, but i think this will work:

  document.querySelectorAll('.datepicker').forEach(t => t.addEventListener('mousedown', e=>e.preventDefault()));

**Comment by ivanvgh** [comment]
> @DanielRuf I'm sorry. I should have been more active and send the patches to these repos myself. I also got this datepicker and slider repo which I recall I had discussion with you about confused.
> 
> Anyhow, the quick fix for this one will be just asking the UA to route the up events to the same input elements that started this with so that the logic of dismissing the popup due to the click handler doesn't get triggered. So before I send the patch and the real fix, could you load [this page](https://amsul.ca/pickadate.js/). I assume this still has the bad behavior here (i.e. popup closing if the user does a long click). Is that right? I'm not familiar with the versioning of this library but I just want to make sure we test the patch on a live example that does show the problem.
> 
> Now just open the devtools and paste this code:
> 
> ```js
> document.querySelector('.picker__input').addEventListener('pointerdown', e=>e.target.setPointerCapture(e.pointerId));
> ```
> 
> It should fix the problem for the first date picker. Do you see any problem after this patch to that page?

you are rigth, but that does not fix the whole problem, but i think this will work:

`document.querySelectorAll('.datepicker').forEach(t => t.addEventListener('mousedown', e=>e.preventDefault()));`

**Comment by ivanvgh** [comment]
> @DanielRuf I'm sorry. I should have been more active and send the patches to these repos myself. I also got this datepicker and slider repo which I recall I had discussion with you about confused.
> 
> Anyhow, the quick fix for this one will be just asking the UA to route the up events to the same input elements that started this with so that the logic of dismissing the popup due to the click handler doesn't get triggered. So before I send the patch and the real fix, could you load [this page](https://amsul.ca/pickadate.js/). I assume this still has the bad behavior here (i.e. popup closing if the user does a long click). Is that right? I'm not familiar with the versioning of this library but I just want to make sure we test the patch on a live example that does show the problem.
> 
> Now just open the devtools and paste this code:
> 
> ```js
> document.querySelector('.picker__input').addEventListener('pointerdown', e=>e.target.setPointerCapture(e.pointerId));
> ```
> 
> It should fix the problem for the first date picker. Do you see any problem after this patch to that page?

`  document.querySelectorAll('.datepicker').forEach(t => t.addEventListener('mousedown', e=>e.preventDefault()));
`

**Comment by ivanvgh** [comment]
> @DanielRuf I'm sorry. I should have been more active and send the patches to these repos myself. I also got this datepicker and slider repo which I recall I had discussion with you about confused.
> 
> Anyhow, the quick fix for this one will be just asking the UA to route the up events to the same input elements that started this with so that the logic of dismissing the popup due to the click handler doesn't get triggered. So before I send the patch and the real fix, could you load [this page](https://amsul.ca/pickadate.js/). I assume this still has the bad behavior here (i.e. popup closing if the user does a long click). Is that right? I'm not familiar with the versioning of this library but I just want to make sure we test the patch on a live example that does show the problem.
> 
> Now just open the devtools and paste this code:
> 
> ```js
> document.querySelector('.picker__input').addEventListener('pointerdown', e=>e.target.setPointerCapture(e.pointerId));
> ```
> 
> It should fix the problem for the first date picker. Do you see any problem after this patch to that page?

You are rigth, but I think this will fix the whole problem:
`  document.querySelectorAll('.datepicker').forEach(t => t.addEventListener('mousedown', e=>e.preventDefault()));
`
